INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (43, 4,  '7292-ntfasfil-ibge.jpg', 'Nota técnica esclarece sobre as diferenças metodológicas entre o Mapa das OSCs e a Fasfil / IBGE', 'Objetivo é explicar a variação quanto ao número de organizações da sociedade civil em atividades no Brasil estabelecido pelo Mapa das OSCs, do Ipea, e pela pesquisa Fasfil / IBGE, divulgada em abril de 2019', '<p>Uma Nota Técnica divulgada pelo Instituto de Pesquisa Econômica Aplicada (Ipea) em agosto de 2019 tem como objetivo descrever os principais aspectos e diferenças metodológicas entre o estudo As Fundações Privadas e Associações sem Fins Lucrativos no Brasil (FASFIL), publicado pelo Instituto Brasileiro de Geografia e Estatística (IBGE), e a plataforma pública de dados Mapa das Organizações da Sociedade Civil (Mapa das OSCs), coordenada pelo Ipea.</p>
<p>De acordo com o estudo FASFIL/IBGE, divulgado em abril de 2019, havia 236 mil fundações privadas e associações sem fins lucrativos no Brasil em 2016. Em relação ao Mapa das OSCs/Ipea, existem 820 mil organizações no país, segundo dados do mesmo ano. Essa variação é explicada, principalmente, pela diferença entre as fontes de informação utilizadas pelos órgãos. Considerando que, apesar das diferenças entre os quantitativos apresentados, as FASFIL e o Mapa das OSCs contemplam o conjunto de entidades sem fins lucrativos pertencentes à sociedade civil, esta nota objetiva detalhar as bases de dados usadas como referência pelos órgãos, além dos procedimentos adotados na identificação e na classificação das entidades capazes de explicar as razões para a divergência entre o número de instituições presente nos dois casos.</p>
<p>A nota é composta por mais três seções principais: <em>Aspectos gerais das FASFIL e do Mapa das OSCs</em>; <em>Diferenças metodológicas entre FASFIL e Mapa das OSCs e suas implicações</em>; e <em>Considerações finais.</em></p>
<p> </p>
<h4 class="media-heading">Publicação completa</h4>
<p><a title="Baixar a publicação - PDF (0.6 MB)" href="/cms/arquivos/publications/5574-ntfasfil-mapa.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publicação - PDF (0.6 MB)</a></p>
<p> </p>
<p> </p>', '5574-ntfasfil-mapa.pdf', '2019-08-17', 1, 3, '2019-09-25 20:53:26', '2019-09-25 21:02:29');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (1, 4,  '9206-perfil-das-osc-no-brasil.png', 'Perfil das Organizações da Sociedade Civil do Brasil: um retrato do setor', 'Publicação traz dados inéditos sobre as principais características das OSCs em atividades no país hoje, bem como informações sobre recursos públicos transferidos, vínculos de trabalho, entre outras.', '<div class="row">
<div class="col-md-12">
<div class="text-justify txtBloco">
<p style="text-align: justify;">Um retrato atual sobre o universo da sociedade civil organizada do pa&iacute;s. Esse &eacute; o objetivo da publica&ccedil;&atilde;o Perfil das Organiza&ccedil;&otilde;es da Sociedade Civil do Brasil. In&eacute;dita, a obra &eacute; resultado do trabalho conjunto entre a equipe do Mapa das OSCs e especialistas no tema. O objetivo &eacute; reunir informa&ccedil;&otilde;es estruturadas e dados estat&iacute;sticos que fomentem estudos anal&iacute;ticos do setor, possam servir de subs&iacute;dio para pol&iacute;ticas p&uacute;blicas envolvendo OSCs, bem como fonte de informa&ccedil;&atilde;o para pesquisas cient&iacute;ficas e muitas outras a&ccedil;&otilde;es. No total, s&atilde;o 12 cap&iacute;tulos, que detalham desde a metodologia empregada na reuni&atilde;o dos dados at&eacute; an&aacute;lises tabelas e gr&aacute;ficos informativos e perspectivas da &aacute;rea.</p>
<p style="text-align: justify;">S&atilde;o in&uacute;meros os resultados. Abaixo, listamos os principais:</p>
</div>
</div>
</div>
<div class="row" style="text-align: justify;">&nbsp;</div>
<div class="row">
<div class="col-md-12">
<div class="text-justify txtBloco">
<ul>
<li style="text-align: justify;"><strong>Quantidade:</strong> Desde 2016, existem 820 mil Organiza&ccedil;&otilde;es da Sociedade Civil (OSCs) mapeadas no Brasil a partir de dados n&atilde;o apenas da Rela&ccedil;&atilde;o Anual de Informa&ccedil;&otilde;es Sociais do Minist&eacute;rio do Trabalho (RAIS-MTE), mas tamb&eacute;m do Cadastro Nacional de Pessoas Jur&iacute;dicas (CNPJ) da Secretaria da Receita Federal.</li>
</ul>
<ul>
<li style="text-align: justify;"><strong>Distribui&ccedil;&atilde;o geogr&aacute;fica:</strong> A disposi&ccedil;&atilde;o das OSCs pelo pa&iacute;s acompanha, em geral, o arranjo da popula&ccedil;&atilde;o. A regi&atilde;o Sudeste abriga 40% das organiza&ccedil;&otilde;es, seguida por Nordeste (25%), Sul (19%), Centro-Oeste (8%) e a regi&atilde;o Norte (8%). Com rela&ccedil;&atilde;o &agrave; localiza&ccedil;&atilde;o das entidades nas cidades, diferentemente do esperado, n&atilde;o h&aacute; concentra&ccedil;&atilde;o de OSCs nas capitais, que abrigam 24% da popula&ccedil;&atilde;o brasileira e 22,5% das OSCs do pa&iacute;s. Todos os 5.570 munic&iacute;pios do pa&iacute;s possuem, pelo menos, uma organiza&ccedil;&atilde;o.</li>
</ul>
<ul>
<li style="text-align: justify;"><strong>&Aacute;rea de atua&ccedil;&atilde;o:</strong>&nbsp;Desenvolvimento e defesa de direitos e interesses e Religi&atilde;o s&atilde;o as principais finalidades das OSCs em funcionamento no Brasil hoje, representando seis em cada dez organiza&ccedil;&otilde;es em atividade. As 339.104 organiza&ccedil;&otilde;es ligadas &agrave; defesa de direitos e interesses representam 41.3% do total e est&atilde;o distribu&iacute;das da seguinte forma, de acordo com a regi&atilde;o: Nordeste: 108.337; Sudeste: 104.526; Sul: 71.424; Norte: 31.950; Centro-Oeste: 22.867. J&aacute; as 208.325 mil OSCs com finalidades religiosas s&atilde;o 25,4% do total e est&atilde;o localizadas, segundo a regi&atilde;o, assim: Sudeste: 112.713; Nordeste: 35.025; Sul: 27.677; Centro-Oeste: 19.353; Norte: 13.557.</li>
</ul>
<ul>
<li style="text-align: justify;"><strong>Natureza jur&iacute;dica:</strong>&nbsp;Do universo das OSCs, 709 mil (86%) s&atilde;o associa&ccedil;&otilde;es privadas, 99 mil (12%) s&atilde;o organiza&ccedil;&otilde;es religiosas e 12 mil (2%) s&atilde;o funda&ccedil;&otilde;es. A distribui&ccedil;&atilde;o entre naturezas jur&iacute;dicas das entidades n&atilde;o difere da disposi&ccedil;&atilde;o das OSCs no territ&oacute;rio, exceto por uma concentra&ccedil;&atilde;o um pouco maior de funda&ccedil;&otilde;es (43%) e um pouco menor de associa&ccedil;&otilde;es (38%) na regi&atilde;o Sudeste, comparado ao total de OSCs, que &eacute; de 40%.</li>
</ul>
<ul>
<li style="text-align: justify;"><strong>V&iacute;nculos empregat&iacute;cios:</strong>&nbsp;83% das OSCs n&atilde;o apresentam v&iacute;nculos formais de emprego; outros 7% delas t&ecirc;m at&eacute; dois v&iacute;nculos de trabalho, totalizando 90% de OSCs que possuem at&eacute; dois v&iacute;nculos. De acordo com dados da RAIS/TEM, em 2015, havia quase tr&ecirc;s milh&otilde;es de pessoas com v&iacute;nculos de emprego nas organiza&ccedil;&otilde;es espalhadas pelo p&aacute;is. Cerca de 60% das pessoas ocupadas em OSCs residiam na regi&atilde;o Sudeste e mais de 50% das organiza&ccedil;&otilde;es com v&iacute;nculos de emprego tamb&eacute;m. Somente o Estado de S&atilde;o Paulo possui quase um ter&ccedil;o das OSCs com v&iacute;nculos de trabalho e mais de 35% das pessoas empregadas nas entidades. As organiza&ccedil;&otilde;esde Sa&uacute;de e Educa&ccedil;&atilde;o s&atilde;o as que mais empregam &ndash; apesar de corresponderem a menos de 10% do universo de OSCs na RAIS (3% e 7%, respectivamente), respondiam por 40% do total de pessoas ocupadas, em 2015.</li>
</ul>
<ul>
<li style="text-align: justify;"><strong>Perfil social dos trabalhadores:</strong>&nbsp;Sobre o perfil das pessoas empregadas por OSCs, em 2015, 66% n&atilde;o tinham n&iacute;vel superior completo; 13% possu&iacute;am o n&iacute;vel fundamental e 49% detinham o n&iacute;vel m&eacute;dio completo. As mulheres predominam entre as pessoas empregadas em OSCs: representam 65% (no Rio Grande do Sul e em Santa Catarina encontram-se a maior propor&ccedil;&atilde;o de mulheres ocupadas e no Amazonas, a menor) e recebem, em m&eacute;dia, 85% do sal&aacute;rio de homens. Com rela&ccedil;&atilde;o ao crit&eacute;rio de ra&ccedil;a, 63% das pessoas ocupadas nas entidades s&atilde;o brancas e 37% de negras (nas regi&otilde;es Norte e Nordeste, h&aacute; predomin&acirc;ncia de negros: 75% e 70%, respectivamente). A contrata&ccedil;&atilde;o de pessoas com defici&ecirc;ncia varia de modo significativo em OSCs de diferentes finalidades e entre grupos de uma mesma finalidade &ndash; o percentual de contra&ccedil;&atilde;o atinge seu m&aacute;ximo na categoria Defesa de direitos e interesses &ndash; m&uacute;ltiplas &aacute;reas e seu m&iacute;nimo em Associa&ccedil;&otilde;es de produtores rurais.</li>
</ul>
<ul>
<li style="text-align: justify;"><strong>Perfil financeiro dos trabalhadores:</strong> A remunera&ccedil;&atilde;o m&eacute;dia para o universo dos trabalhadores assalariados em OSCs era de R$ 2.869, equivalentes &agrave; 3,2 sal&aacute;rios m&iacute;nimos. O valor &eacute; maior nas organiza&ccedil;&otilde;es cuja finalidade de atua&ccedil;&atilde;o &eacute; a Sa&uacute;de (3,8 SMs), Associa&ccedil;&otilde;es Patronais e Profissionais (3,7 SMs) e Educa&ccedil;&atilde;o e Pesquisa (3,7 SMs) &ndash; e menor em organiza&ccedil;&otilde;es da finalidade Assist&ecirc;ncia Social (1,9 SMs). A remunera&ccedil;&atilde;o m&eacute;dia dos ocupados na regi&atilde;o Sul e Sudeste (respectivamente R$ 2.798 e R$ 2.881) s&atilde;o superiores &agrave;s demais.</li>
</ul>
<ul>
<li style="text-align: justify;"><strong>Parcerias financeiras com o governo federal:</strong>&nbsp;Entre 2010 e 2017 foram transferidos da Uni&atilde;o para as Organiza&ccedil;&otilde;es da Sociedade Civil (OSCs) o total de R$ 75 bilh&otilde;es. Sa&uacute;de e Educa&ccedil;&atilde;o receberam quase 50% deste valor. A distribui&ccedil;&atilde;o dos recursos federais, por regi&atilde;o, &eacute; mais concentrada que a localiza&ccedil;&atilde;o territorial das OSCs. Vale lembrar que a &aacute;rea de atua&ccedil;&atilde;o das OSCs n&atilde;o est&aacute; restrita &agrave; localiza&ccedil;&atilde;o da sede das organiza&ccedil;&otilde;es. Entretanto, quando considerada a regi&atilde;o onde est&atilde;o localizadas as sedes das OSCs, os dados demonstram grandes diferen&ccedil;as regionais. A regi&atilde;o Sudeste, por exemplo, &eacute; indicada como sede de 42% das OSCs, e recebeu 61% do total de recursos federais transferidos. Concentra&ccedil;&atilde;o ainda mais alta ocorreu no interior da regi&atilde;o Centro-Oeste: as OSCs com sede no Distrito Federal receberam 83% de todos os recursos destinados &agrave; regi&atilde;o, apesar de abrigar apenas 22% das organiza&ccedil;&otilde;es.</li>
</ul>
<p style="text-align: justify;">&nbsp;</p>
<p><strong>Publica&ccedil;&atilde;o completa</strong>&nbsp;</p>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/pdf/publicacao-IPEA-perfil-osc-Brasil.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF (3.9 MB)</a></p>
</div>
</div>
</div>', '', '2018-04-19', 1, 3, '2018-08-01 14:26:33', '2019-05-02 00:48:24');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (17, 4,  '9353-publicacao-uflaipea.png', 'Platform of the Brazilian CSOs: Open Government Data and Crowdsourcing for the Promotion of Citizenship', 'Artigo sobre o Mapa das OSCs publicado no XIII Brazilian Symposium of Information Systems enfatiza a importância de dados sistematizados para fortalecimento e visibilidade das organizações', '<p style="text-align: justify;">No Brasil e no mundo, as organiza&ccedil;&otilde;es da sociedade civil (CSOs) fornecem servi&ccedil;os p&uacute;blicos valiosos para a sociedade.&nbsp;Por meio das OSCs, as pessoas se organizam e defendem seus direitos, comunidades e interesses, e podem exercer plenamente seu potencial coletivo, muitas vezes atuando em parceria com&nbsp;governos para realizar pol&iacute;ticas p&uacute;blicas e/ou desenvolver seus pr&oacute;prios projetos, auto-financiados ou financiados por institui&ccedil;&otilde;es p&uacute;blicas ou privadas. A transpar&ecirc;ncia p&uacute;blica e a disponibilidade de dados de qualidade s&atilde;o requisitos para analisar a for&ccedil;a e&nbsp;capacidade dessas organiza&ccedil;&otilde;es.&nbsp;&nbsp;</p>
<p style="text-align: justify;">Compreender a distribui&ccedil;&atilde;o&nbsp;de OSCs em todo o mundo&nbsp;e na escala nacional, suas &aacute;reas de atualiza&ccedil;&atilde;o, projetos em&nbsp;progresso, e sua capacidade de execu&ccedil;&atilde;o, &eacute; fundamental para promover&nbsp;as condi&ccedil;&otilde;es de financiamento das OSCs, para torn&aacute;-las vis&iacute;veis e mais eficazes, transparentes e fortes. Com esses objetivos em mente, desenvolvemos o Mapa das Organiza&ccedil;&otilde;es da Sociedade Civil,&nbsp;uma plataforma online aberta, livre e p&uacute;blica, que fornece uma ampla variedade de informa&ccedil;&otilde;es sobre o perfil&nbsp;e desempenho da popula&ccedil;&atilde;o das OSC no Brasil.</p>
<p style="text-align: justify;">O artigo "Platform of the Brazilian CSOs: Open Government Data and Crowdsourcing for the Promotion of Citizenship", produzido em conjunto por uma equipe de pesquisadores do Ipea e publicado no XIII Brazilian Symposium of Information Systems em Lavras - MG, de 2017, conta um pouco desse projeto.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/7728-proceedingscompletoipea-cp.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a Publica&ccedil;&atilde;o - PDF (1.2 MB)</a></p>', '7728-proceedingscompletoipea-cp.pdf', '2017-06-05', 1, 3, '2018-09-10 18:53:34', '2019-05-02 00:50:23');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (41, 4,  '6278-gestaolivro.jpg', 'Coletânea comemora 21 anos de núcleo de estudos sobre o Terceiro Setor', 'Intitulado "Gestão de Organizações da Sociedade Civil", livro lançado em agosto de 2019 reúne artigos de professores e pesquisadores do Núcleo de Estudos Avançados em Terceiro Setor (Neats), da PUC-SP', '<p>O livro <em>Gest&atilde;o de Organiza&ccedil;&otilde;es da Sociedade Civil</em>, do N&uacute;cleo de Estudos Avan&ccedil;ados em Terceiro Setor (Neats) da Pontif&iacute;cia Univerisdade Cat&oacute;lica de S&atilde;o Paulo (PUC-SP), foi lan&ccedil;ado no dia 05&nbsp;de setembro de 2019, em S&atilde;o Paulo. A colet&acirc;nea, organizada por Luciano Ant&ocirc;nio Prates Junqueira e Roberto Sanches Padula, re&uacute;ne 14 artigos de professores e pesquisadores do Neats e&nbsp;celebra os 21 anos de atividades do grupo.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF (1.2 MB)" href="/cms/arquivos/publications/6710-gestaooscsneats1p.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF (1.2 MB)</a></p>
<p>&nbsp;</p>', '6710-gestaooscsneats1p.pdf', '2019-09-10', 1, 3, '2019-09-24 21:38:35', '2019-09-25 13:30:50');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (19, 4,  '8720-posterperfilipea.png', 'Estudo aponta o perfil demográfico e a escolaridade dos trabalhadores formais das OSCs', 'Resultados obtidos através dos dados da Rais Ampliada de 2015, indicam que o mercado de trabalho formal das OSCs é majoritariamente feminino, exceto para organizações que atuam na em Cultura e Arte.', '<p style="text-align: justify;">O objetivo do artigo "O perfil demogr&aacute;fico e a escolaridade dos trabalhadores formais das OSCs em 2015, elaborado por um grupo de pesquisadores do Ipea,&nbsp;&eacute; apresentar o retrato in&eacute;dito sobre o perfil demogr&aacute;fico e a escolaridade do universo de trabalhadores vinculados ao mercado de trabalho formal das&nbsp;organiza&ccedil;&otilde;es em atividade no pa&iacute;s.</p>
<p style="text-align: justify;">O trabalho &eacute; justificado n&atilde;o s&oacute; pelo seu ineditismo, mas tamb&eacute;m pela contribui&ccedil;&atilde;o ao debate sobre OSCs. Os resultados obtidos&nbsp;por meio dos dados da Rais Ampliada de 2015, indicam que o mercado de trabalho formal das OSCs &eacute; majoritariamente feminino, exceto para organiza&ccedil;&otilde;es que atuam na em Cultura e Arte.</p>
<p style="text-align: justify;">Os n&iacute;veis de escolaridade e distribui&ccedil;&atilde;o et&aacute;ria dos trabalhadores em OSCs s&atilde;o bastante distintos, entre as diferentes finalidades de atua&ccedil;&atilde;o e por sexo. Em todas as finalidades de atua&ccedil;&atilde;o observou-se maior escolaridade das mulheres em rela&ccedil;&atilde;o aos homens, havendo destaque para as OSCs de &ldquo;educa&ccedil;&atilde;o e pesquisa&rdquo;, que tiveram maior escolariza&ccedil;&atilde;o que as demais, independente do sexo. As regi&otilde;es Sul e Sudeste foram as que tiveram maior percentual da popula&ccedil;&atilde;o com n&iacute;vel superior.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/3286-oscsabepv5.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF (0.7 MB)</a></p>', '3286-oscsabepv5.pdf', '2018-09-27', 1, 3, '2018-10-01 19:29:20', '2019-05-02 00:31:53');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (12, 4,  '6210-giving-report-2017-brasil.png', 'Giving report 2017 Brasil: Um retrato da doação no Brasil', 'A CAF criou o CAF World Giving Index (Índice Global de Solidariedade), o principal estudo comparativo global sobre solidariedade, cujos dados mostram mudanças nas doações ao redor do mundo.', '<p style="text-align: justify;">A CAF criou o CAF World Giving Index (&Iacute;ndice Global de Solidariedade), o principal estudo comparativo global sobre solidariedade, cujos dados mostram mudan&ccedil;as nas doa&ccedil;&otilde;es ao redor do mundo e fornecem um forte foco para o seu crescimento.</p>
<p style="text-align: justify;">Desde s&eacute;culo passado at&eacute; os nossos dias, o mundo tem presenciado uma ascens&atilde;o do papel representado por organiza&ccedil;&otilde;es da sociedade civil que, cada vez mais, s&atilde;o instrumentos de express&atilde;o dos anseios da popula&ccedil;&atilde;o.&nbsp;No Brasil n&atilde;o &eacute; diferente. Aqui, tamb&eacute;m verifica-se o aumento do protagonismo da sociedade civil e de suas organiza&ccedil;&otilde;es. Por&eacute;m, para que essas institui&ccedil;&otilde;es consigam continuar representando os desejos e pensamentos da popula&ccedil;&atilde;o de forma independente, precisam contar com o apoio dos indiv&iacute;duos, n&atilde;o s&oacute; com doa&ccedil;&atilde;o de tempo, trabalho, conhecimento e influ&ecirc;ncia, mas tamb&eacute;m com recursos financeiros.&nbsp;Por isso, s&atilde;o t&atilde;o importantes as pesquisas que mapeiam e nos ajudam a entender o comportamento e as motiva&ccedil;&otilde;es do doador brasileiro.</p>
<p style="text-align: justify;">O IDIS Instituto para o Desenvolvimento do Investimento Social, junto com uma s&eacute;rie de parceiros, realizou a Pesquisa Doa&ccedil;&atilde;o Brasil, a primeira pesquisa de abrang&ecirc;ncia nacional sobre os h&aacute;bitos do doador em nosso pa&iacute;s.&nbsp;</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/1801-country-giving-report-2017-brasil.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF (0.9 MB)</a></p>', '1801-country-giving-report-2017-brasil.pdf', '2017-06-26', 1, 3, '2018-09-05 14:58:22', '2019-05-02 00:35:19');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (9, 4,  '4096-destaque-2017-uma-restrospectiva-da-atuacao-sc-10-anos.png', 'Pesquisa BISC 2017: uma retrospectiva da atuação social corporativa nos últimos dez anos', 'O estudo, liderado pela Comunitas, busca dimensionar todos os recursos, financeiros e em bens e serviços, aplicados pelas empresas em projetos e atividades de interesse social.', '<p style="text-align: justify;">A pesquisa sobre o Benchmarking do Investimento Social Corporativo &ndash; BISC, busca dimensionar todos os recursos, financeiros e em bens e servi&ccedil;os, aplicados pelas empresas em projetos e atividades de interesse social. Iniciada em 2008, &eacute; o resultado de uma parceria entre a Comunitas e um conjunto selecionado de empresas. &Eacute; realizada anualmente e tem por objetivo contribuir para o desenvolvimento, o aperfei&ccedil;oamento da gest&atilde;o e a avalia&ccedil;&atilde;o dos investimentos sociais corporativos no Brasil.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/1438-bisc2017digitalfinalcp.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a Publica&ccedil;&atilde;o - PDF (0.9 MB)</a></p>', '1438-bisc2017digitalfinalcp.pdf', '2017-03-25', 1, 3, '2018-09-05 14:41:18', '2019-05-02 00:49:43');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (66, 4,  '6760-cartilha2020.jpg', 'Cartilha ilustrada explica como funciona o Mapa das OSCs', 'Com linguagem simples, publicação tem dez páginas e informa sobre a origem e características do Mapa, as formas de abastecimento das informações, o público alvo, o conteúdo etc.', '<p>O&nbsp;<em>Mapa das Organiza&ccedil;&otilde;es da Sociedade Civil</em>&nbsp;lan&ccedil;ou em fevereiro de 2020 uma cartilha com o objetivo principal de explicar como funciona a plataforma. Totalmente ilustrada e com linguagem acess&iacute;vel, a publica&ccedil;&atilde;o cont&eacute;m 10 p&aacute;ginas e informa sobre a origem e caracter&iacute;sticas do Mapa, as formas de abastecimento das informa&ccedil;&otilde;es, o p&uacute;blico alvo, o conte&uacute;do etc.</p>
<p>Esta &eacute; a segunda vez que o Mapa produz uma cartilha voltada, principalmente, para o p&uacute;blico das OSCs, que precisa conhecer e se familiarizar com o Mapa e manter as p&aacute;ginas de suas organiza&ccedil;&otilde;es atualizadas. A primeira vers&atilde;o foi publicada em 2017. A vers&atilde;o atual, por&eacute;m, est&aacute; mais did&aacute;tica e objetiva e foi feita com base nas d&uacute;vidas e sugest&otilde;es enviadas pelos pr&oacute;prios membros das OSCs na se&ccedil;&atilde;o &ldquo;Fale conosco&rdquo;.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a href="/cms/arquivos/publications/8974-cartilhafinalmapa2020comp.pdf" target="_blank"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a cartilha - PDF</a></p>', '8974-cartilhafinalmapa2020comp.pdf', '2020-02-03', 1, 3, '2020-04-24 20:48:56', '2020-04-24 20:53:18');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (45, 4,  '5657-ntatualizacao2019.jpg', 'Por dentro do Mapa das OSCs: Metodologia da base de dados (versão 2019)', 'Publicação traz o detalhamento dos processos metodológicos referente à atualização das bases de dados do Mapa das OSCs, realizada em 2019. Principal fonte é o universo de CNPJs ativos disponibilizados pela SRFB', '<h2> </h2>
<p>A identificação de OSCs no Mapa utiliza o universo de CNPJs (Cadastro Nacional de Pessoa Jurídica) ativos no país e que são disponibilizados pela Secretaria da Receita Federal do Brasil (SRFB). A extração de informações para atualização do Mapa é realizada a cada dois anos e, na versão 2.9 (implantada em novembro de 2019), refere-se à base do CNPJ, mês de referência novembro de 2018. Veja na publicação todos os procedimentos metodológicos.</p>
<p> </p>
<h4 class="media-heading">Publicação completa</h4>
<p> </p>
<p><a href="/cms/arquivos/publications/1864-notatecnicaatualizacao2019-2.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publicação - PDF</a></p>
<p> </p>', '1864-notatecnicaatualizacao2019-2.pdf', '2019-11-21', 1, 3, '2019-11-21 19:35:15', '2019-11-21 19:46:16');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (68, 4,  '7918-bapi22.jpg', 'Publicação do Ipea reúne textos com recomendações de políticas públicas em época de Covid-19', 'Edição temática do Boletim de Análise Político-Institucional (Bapi) tem por objetivo reunir diversas contribuições ao debate sobre a crise do coronavírus, seus efeitos e medidas necessárias ao seu enfrentamento', '<p>O Instituto de Pesquisa Econ&ocirc;mica Aplicada (Ipea) lan&ccedil;ou uma edi&ccedil;&atilde;o tem&aacute;tica do Boletim de An&aacute;lise Pol&iacute;tico-Institucional (Bapi)&nbsp;sobre a Covid-19. O objetivo &eacute;&nbsp;reunir diversas contribui&ccedil;&otilde;es ao debate sobre a crise do coronav&iacute;rus no Brasil, seus efeitos e, principalmente, medidas necess&aacute;rias ao seu enfrentamento. S&atilde;o, no total, nove textos,&nbsp;oriundos de diversas &aacute;reas do conhecimento.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/7365-bapi22comp.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>', '7365-bapi22comp.pdf', '2020-05-07', 1, 3, '2020-05-19 20:14:17', '2020-05-19 20:17:52');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (42, 4,  '6181-fortalecimentofgv.jpg', 'Novo livro aborda o fortalecimento da Sociedade Civil: da redução de barreiras tributárias às doações', 'A obra tem 214 páginas e é dividida em quatro capítulos. Foi lançada em setembro de 2019 pela FGV Direito-SP como mais um volume da coleção Sustentabilidade Econômica das Organizações da Sociedade Civil', '<p>A FGV Direito São Paulo lançou o livro <em>Fortalecimento da Sociedade Civil: redução de barreiras tributárias às doações</em>. A obra, coordenada por Aline Gonçalves de Souza, Aline Viotto e Eduardo Pannunzio, integra a coleção Sustentabilidade Econômica das Organizações da Sociedade Civil e apresenta os resultados das pesquisas desenvolvidas no âmbito do projeto homônimo, desenvolvido pelo Grupo de Institutos, Fundações e Empresas (GIFE) em parceria com a Coordenadoria de Pesquisa Jurídica Aplicada da FGV Direito São Paulo, com o Ipea, entre outros. </p>
<p>O volume tem 214 páginas e está dividido em quatro capítulos: <em>A experiência internacional na tributação de doações para Organizações da Sociedade Civil</em>;<em> O imposto sobre doações nos estados brasileiros e Distrito Federal: panorama legal</em>;<em> A jurisprudência dos Tribunais Superiores </em>e<em> Arrecadação do ITCMD no Brasil</em>; e<em> Doações a OSC: informações disponíveis</em>. Promete ser o primeiro de uma série.</p>
<p> </p>
<h4 class="media-heading">Publicação completa</h4>
<p><a title="Baixar a publicação - PDF (2.0 MB)" href="https://sinapse.gife.org.br/download/fortalecimento-da-sociedade-civil-reducao-de-barreiras-tributarias-as-doacoes"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publicação - PDF (2.0 MB)</a></p>
<p> </p>', '', '2019-09-16', 1, 3, '2019-09-25 12:51:56', '2019-09-25 13:29:21');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (81, 4,  '4155-ososcip.jpg', 'Relatório do Mapa das OSCs traça o perfil das OSs e OSCIPs em atividade no Brasil', 'Documento reúne informações como: localização geográfica, área de atuação, vínculos de trabalho, repasses federais etc., a partir de dados provenientes de bases da SRF, RAIS e do Orçamento Público Federal', '<p style="text-align: justify;">Desde o fim da d&eacute;cada de 1990, os t&iacute;tulos de Organiza&ccedil;&atilde;o Social (OS) ou Organiza&ccedil;&atilde;o da Sociedade Civil de Interesse P&uacute;blico (OSCIP) s&atilde;o outorgados a organiza&ccedil;&otilde;es da sociedade civil (OSCs) pela Administra&ccedil;&atilde;o P&uacute;blica municipal, estadual ou federal. O objetivo &eacute; garantir juridicamente que a entidade possa receber benef&iacute;cios de governos e &oacute;rg&atilde;os p&uacute;blicos (na forma de estabelecimento de parcerias, dota&ccedil;&otilde;es or&ccedil;ament&aacute;rias, isen&ccedil;&otilde;es fiscais etc.) para a realiza&ccedil;&atilde;o de suas atividades, que devem ser, necessariamente, de interesse coletivo da sociedade.</p>
<p style="text-align: justify;">Atualmente, h&aacute; 781.921 OSCs formais, ou seja, com Cadastro Nacional de Pessoa Jur&iacute;dica (CNPJ), em atividade no Brasil. Dessas, 1.114 s&atilde;o OSs e 7.046 s&atilde;o OSCIPs. Pensando em descrever melhor esse universo, o Mapa das OSCs produziu um relat&oacute;rio que tra&ccedil;a o perfil dessas entidades. O documento re&uacute;ne informa&ccedil;&otilde;es como: localiza&ccedil;&atilde;o geogr&aacute;fica, &aacute;rea de atua&ccedil;&atilde;o, v&iacute;nculos de trabalho, repasses federais etc., com base em dados provenientes de bases da&nbsp;Secretaria da Receita Federal (SRF), da Rela&ccedil;&atilde;o Anual de Informa&ccedil;&otilde;es Sociais (RAIS) e do Or&ccedil;amento P&uacute;blico Federal. &nbsp;</p>
<h4 class="media-heading" style="text-align: justify;">Publica&ccedil;&atilde;o completa</h4>
<p><a href="/cms/arquivos/publications/1915-relatorioososcipfinal.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>
<p>&nbsp;</p>', '1915-relatorioososcipfinal.pdf', '2020-07-15', 1, 3, '2020-07-15 19:53:49', '2020-08-07 16:45:01');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (29, 4,  '6227-publicacaovoluntarios.jpg', 'País tem 7,2 milhões de trabalhadores voluntários, diz IBGE', 'De acordo com o suplemento Outras Formas de Trabalho, da Pesquisa Nacional de Amostra por Domicílios Contínua, o total de voluntários em 2018 representou 4,3% da população com 14 anos ou mais.', '<p>O Brasil teve 7,2 milh&otilde;es de pessoas praticando trabalho volunt&aacute;rio em 2018. A informa&ccedil;&atilde;o &eacute; do suplemento Outras Formas de Trabalho, da Pesquisa Nacional de Amostra por Domic&iacute;lios Cont&iacute;nua, divulgado pelo IBGE. De acordo com o estudo,&nbsp;O total de volunt&aacute;rios no ano representou 4,3% da popula&ccedil;&atilde;o com 14 anos ou mais. A incid&ecirc;ncia foi maior entre mulheres, 5% delas faziam trabalho volunt&aacute;rio; pessoas com 50 anos ou mais, 5%; e superior completo, 8%.</p>
<h4 class="media-heading">Principais dados</h4>
<p><a class="btn" title="Baixar os resultados" href="/cms/arquivos/publications/9751-trabalhovoluntario.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar os resultados</a></p>', '9751-trabalhovoluntario.pdf', '2019-04-30', 1, 1, '2019-05-01 22:50:52', '2019-05-13 21:54:50');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (82, 4,  '6562-mobiliza.jpg', 'Pesquisa aponta impactos da Covid-19 nas OSCs', 'Estudo, realizado pela consultoria Mobiliza e a instituição ReosPartners, foi feito com 1.760 organizações e revelou, entre outros dados, como a crise causada pela pandemia enfraqueceu as entidades', '<p style="text-align: justify;">Um estudo realizado pela consultoria Mobiliza e a instituição ReosPartners, divulgado neste mês de agosto, analisou o impacto da Covid-19 nas OSCs brasileiras. A pesquisa foi realizada com 1.760 representantes de organizações de todas as regiões do país, a partir de formulário de perguntas fechadas, complementado com algumas entrevistas. Entre os principais resultados, destaca-se que, 87% das OSCs relataram ter todas ou parte de suas atividades regulares interrompidas ou suspensas por conta da crise; e 73% das OSCs informaram que a crise as enfraqueceu. Chama a atenção entre os dados levantados que, mesmo com as restrições financeiras, até o final de 2020 a maioria das organizações respondentes (87%) prevê continuar as atividades.</p>
<p style="text-align: justify;"> </p>
<h4 class="media-heading">Publicação completa</h4>
<p><a title="Baixar a publicação - PDF" href="/cms/arquivos/publications/1349-mobiliza.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publicação - PDF</a></p>', '1349-mobiliza.pdf', '2020-08-14', 1, 3, '2020-08-17 01:20:43', '2020-08-17 01:27:38');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (23, 4,  '9251-extratordadosn.png', 'test', 't', '<p>test</p>', '8514-fasfilmapa.pdf', '2019-04-15', 0, 1, '2019-04-15 21:59:36', '2019-04-15 22:01:11');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (76, 4,  '5435-fundraisingprinciples.jpg', 'Publicação reúne informações para regulamentação e auto-regulação da captação de recursos', 'Documento (em inglês) é baseado em pesquisas sobre tópicos como auto-regulação, licenciamento, permissão, regulamentação da captação digital de recursos, proteção de dados, entre outros', '<p style="text-align: justify;">O European Center for Not-for-Profit Law (ECNL) e o The International Center for Not-for-Profit Law (ICNL) lan&ccedil;aram, em conjunto, o documento Principles for statutory regulation and self-regulation of fundrasing, em portugu&ecirc;s algo como "Princ&iacute;pios para regulamenta&ccedil;&atilde;o estatut&aacute;ria e auto-regula&ccedil;&atilde;o da capta&ccedil;&atilde;o de recursos". O objetivo da publica&ccedil;&atilde;o &eacute; fornecer uma vis&atilde;o global das tend&ecirc;ncias atuais da regulamenta&ccedil;&atilde;o e auto-regula&ccedil;&atilde;o das pr&aacute;ticas de capta&ccedil;&atilde;o de recursos e apoiar os esfor&ccedil;os de advocacy para criar um ambiente prop&iacute;cio para essa pr&aacute;tica em todo o mundo.</p>
<p style="text-align: justify;">O documento foi desenvolvido com o apoio de um grupo de especialistas no tema e baseado em pesquisas sobre t&oacute;picos como auto-regula&ccedil;&atilde;o, licenciamento, permiss&atilde;o, procedimentos de notifica&ccedil;&atilde;o para fins de capta&ccedil;&atilde;o de recursos, regulamenta&ccedil;&atilde;o da capta&ccedil;&atilde;o digital de recursos, prote&ccedil;&atilde;o de dados e outros. Apresenta os seguintes princ&iacute;pios e recomenda&ccedil;&otilde;es: 1) Garantias fundamentais; 2) M&eacute;todos de capta&ccedil;&atilde;o de recursos; 3) Prote&ccedil;&atilde;o de dados e direito &agrave; privacidade; 4) Capta&ccedil;&atilde;o de recursos transfronteiri&ccedil;os; 5) Tributa&ccedil;&atilde;o; 6) Transpar&ecirc;ncia, presta&ccedil;&atilde;o de contas e supervis&atilde;o; e 7) Registro, licenciamento e permiss&atilde;o.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF" href="/cms/arquivos/publications/7890-fundraisingprinciplescompac.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>', '7890-fundraisingprinciplescompac.pdf', '2020-06-24', 1, 3, '2020-06-29 18:34:16', '2020-06-29 21:35:29');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (85, 4,  '1422-bisc2020.jpg', 'Relatório BISC 2020 aponta crescimento de 13% nos investimentos sociais no Brasil', 'Pesquisa chega à sua 13ª edição e reúne um conjunto de informações que permitem aferir a evolução dos investimentos sociais privados no país, os avanços obtidos e os
desafios que se apresentam, especialmente em um contexto de pandemia, como o vivido em 2020', '<p style="text-align: justify;">Em 2020, a pesquisa BISC &ndash; Benchmarking do Investimento Social Corporativo &ndash; chega &agrave; sua 13&ordf; edi&ccedil;&atilde;o e re&uacute;ne um conjunto importante de informa&ccedil;&otilde;es que permitem aferir a evolu&ccedil;&atilde;o dos investimentos sociais privados, os avan&ccedil;os obtidos e os desafios que se apresentam, para a participa&ccedil;&atilde;o das empresas no enfrentamento dos problemas sociais do Pa&iacute;s. Inspirada na experi&ecirc;ncia do CECP , institui&ccedil;&atilde;o parceira da Comunitas, a pesquisa foi criada com o objetivo de estabelecer padr&otilde;es de refer&ecirc;ncia para a atua&ccedil;&atilde;o social privada que pudesse ser comparada, nacional e internacionalmente. Ela &eacute; realizada anualmente e busca, a cada edi&ccedil;&atilde;o, introduzir inova&ccedil;&otilde;es que permitam auxiliar os participantes a realizarem uma autoavalia&ccedil;&atilde;o das suas pr&aacute;ticas sociais e identificarem novos caminhos a partir da experi&ecirc;ncia coletiva. Al&eacute;m disso, a pesquisa visa ainda subsidiar a reflex&atilde;o acad&ecirc;mica sobre o tema e hoje &eacute; fonte de inspira&ccedil;&atilde;o para novos estudos na &aacute;rea.</p>
<p style="text-align: justify;">&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF" href="/cms/arquivos/publications/2220-bisc2020relataoriofinaldigital.pdf" target="_blank"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>', '2220-bisc2020relataoriofinaldigital.pdf', '2020-12-30', 1, 3, '2021-03-16 16:41:41', '2021-03-16 17:12:38');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (13, 4,  '4505-mrosc-na-pratica.png', 'MROSC na Prática: Guia de Orientações para Gestoras e Gestores Públicos e para OSCs', 'Publicação é resultado do Projeto Sociedade Civil Construindo a Resistência Democrática, iniciativa da Abong junto às suas associadas Camp, Cese e Cfemea, apoiada pela União Europeia.', '<p style="text-align: justify;">O "MROSC na Pr&aacute;tica: Guia de Orienta&ccedil;&otilde;es para Gestoras e Gestores P&uacute;blicos e para OSCs" &eacute; um dos frutos do Projeto Sociedade Civil Construindo a Resist&ecirc;ncia Democr&aacute;tica, iniciativa da Abong junto &agrave;s suas associadas Camp, Cese e Cfemea, apoiada pela Uni&atilde;o Europeia.</p>
<p style="text-align: justify;">Esta publica&ccedil;&atilde;o se insere no contexto de incid&ecirc;ncia da Abong que, desde o in&iacute;cio de sua constitui&ccedil;&atilde;o, trabalha pela constru&ccedil;&atilde;o de um Marco Regulat&oacute;rio para as Organiza&ccedil;&otilde;es da Sociedade Civil (MROSC), tendo como objeto principal um ambiente pol&iacute;tico de n&atilde;o criminaliza&ccedil;&atilde;o das Organiza&ccedil;&otilde;es da Sociedade Civil (OSCs) brasileiras.</p>
<p style="text-align: justify;">Assim, este guia abre um debate para todas as nossas organiza&ccedil;&otilde;es, tendo como desafio a implementa&ccedil;&atilde;o da Lei 13.019 em todos os estados e munic&iacute;pios e a constru&ccedil;&atilde;o de novas estrat&eacute;gias coletivas. Foi concebido a partir da leitura cr&iacute;tica de decretos e editais publicados j&aacute; na vig&ecirc;ncia da nova lei. Ele n&atilde;o encerra o debate, pelo contr&aacute;rio. Esta &eacute; apenas uma primeira vers&atilde;o para ser lida, usada e confrontada com outras experi&ecirc;ncias e olhares a fim de que seja aperfei&ccedil;oada a compreens&atilde;o e a pr&aacute;tica do MROSC no dia a dia.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/4559-guia-mrosc-gestores.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF (1.6 MB)</a></p>', '4559-guia-mrosc-gestores.pdf', '2017-09-02', 1, 3, '2018-09-05 15:04:44', '2019-05-02 00:40:47');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (63, 4,  '9764-covid19mf.jpg', 'COVID-19: Publicação traça principais impactos para OSCs', 'Material produzido a pedido do Trust Law, programa da Thomson Reuters Foundation, reúne informações e análises em relação às normativas publicadas no contexto de pandemia no Brasil', '<p>Com o objetivo de somar esfor&ccedil;os com a produ&ccedil;&atilde;o de conhecimento em tempos de Covid-19, o escrit&oacute;rio brasileiro Mattos Filho produziu, a pedido do Trust Law, programa da Thomson Reuters Foundation, um documento que re&uacute;ne&nbsp;informa&ccedil;&otilde;es, em v&aacute;rios pa&iacute;ses, sobre (i) impactos jur&iacute;dicos para as organiza&ccedil;&otilde;es da sociedade civil, (ii) prote&ccedil;&atilde;o de dados e iniciativas de fomento &agrave; tecnologia na &aacute;rea da sa&uacute;de e (iii) altera&ccedil;&otilde;es normativas relacionadas &agrave; imigra&ccedil;&atilde;o e ao ref&uacute;gio.O material tem informa&ccedil;&otilde;es e an&aacute;lises em rela&ccedil;&atilde;o &agrave;s normativas publicadas no contexto de pandemia, sempre com as adapta&ccedil;&otilde;es necess&aacute;rias &agrave;s especificidades das organiza&ccedil;&otilde;es da sociedade civil no Brasil.</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/4346-codiv19documentomfcompac.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>', '4346-codiv19documentomfcompac.pdf', '2020-04-14', 1, 3, '2020-04-15 20:47:06', '2020-04-15 20:50:00');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (24, 4,  '5680-publicacaocaf.jpg', 'Pesquisa retrata o comportamento e o pensamento dos brasileiros sobre doação, voluntariado e engajamento', 'Segundo o Relatório Giving Report 2018 Brasil, apesar do registro de avanços, doações no país seguem de forma esporádica, sem comprometimento com a sustentabilidade das OSCs.', '<p>A segunda edi&ccedil;&atilde;o do Brasil Giving Report revela um retrato do comportamento e do pensamento dos brasileiros no que diz respeito a doa&ccedil;&atilde;o, voluntariado e engajamento c&iacute;vico no per&iacute;odo de agosto de 2017 a julho de 2018. O estudo&nbsp;faz parte&nbsp;de uma s&eacute;rie internacional, produzida pela Alian&ccedil;a Global da Charities Aid Foundation (CAF), uma rede mundial de organiza&ccedil;&otilde;es que trabalham nas fronteiras da filantropia e da sociedade civil. No Brasil, o Instituto para o Desenvolvimento do Investimento Social (IDIS) &eacute; uma organiza&ccedil;&atilde;o da sociedade civil de interesse p&uacute;blico (OSCIP) que integra a CAF.&nbsp;</p>
<p>Entre os resultados da pesquisa, destacam-se que:</p>
<ul>
<li>As pessoas no Brasil continuam a doar dinheiro no mesmo ritmo registrado em 2017. Sete em cada dez (70%) doaram dinheiro nos &uacute;ltimos 12 meses, seja a uma organiza&ccedil;&atilde;o social, a uma igreja ou organiza&ccedil;&atilde;o religiosa, ou patrocinando algu&eacute;m.</li>
<li>As causas mais populares permanecem as mesmas do ano passado, com aproximadamente metade dos doadores (52%) apoiando organiza&ccedil;&otilde;es religiosas/igrejas.</li>
<li>A quantia t&iacute;pica doada (mediana) ou patrocinada pelos que fizeram doa&ccedil;&otilde;es nos &uacute;ltimos 12 meses &eacute; de R$200.  A doa&ccedil;&atilde;o em dinheiro &eacute; o m&eacute;todo mais comum, sendo utilizado por cerca de dois ter&ccedil;os dos doadores (68%).</li>
<li>As principais raz&otilde;es para doar permanecem inalteradas desde 2017. &ldquo;Porque faz com que se sintam bem&rdquo; &eacute; a raz&atilde;o mais comum para a doa&ccedil;&atilde;o, com metade das pessoas citando esse motivo.</li>
<li>De forma consistente com os resultados de 2017, mais de metade das pessoas (53%) fez trabalho volunt&aacute;rio nos &uacute;ltimos 12 meses.</li>
<li>A maioria dos entrevistados considera que o impacto das organiza&ccedil;&otilde;es sociais no Brasil &eacute; positivo para as comunidades locais, para o Brasil como um todo e internacionalmente.</li>
<li>&ldquo;Ter mais dinheiro&rdquo; &eacute; o fator mais citado pelos pesquisados como est&iacute;mulo para as pessoas doarem mais tempo, bens ou dinheiro nos pr&oacute;ximos 12 meses (57%).</li>
</ul>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a href="/cms/arquivos/publications/2235-caf-brazil-report-2018.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o PDF</a></p>
<p>&nbsp;</p>', '2235-caf-brazil-report-2018.pdf', '2019-04-12', 1, 3, '2019-04-15 22:31:15', '2019-05-02 00:02:13');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (18, 4,  '9518-filantropia.png', 'Coletânea traz informações sobre filantropia de justiça social, sociedade civil e movimentos sociais', 'Obra organizada por Graciela Hopstein reúne 20 artigos, de autores e pesquisadores de diversas áreas do conhecimento, que trabalham com a temática nos contextos da América Latina e internacional.', '<p style="text-align: justify;">Colet&acirc;nea organizada por Graciela Hopstein procura refletir e trazer &agrave; tona um conjunto de tem&aacute;ticas, problem&aacute;ticas e tend&ecirc;ncias que permeiam os campos da filantropia de justi&ccedil;a social, dos direitos humanos no Brasil, no contexto da Am&eacute;rica Latina e do &acirc;mbito internacional.</p>
<p style="text-align: justify;">Os 20 textos reunidos est&atilde;o organizados em cinco partes: (1) O cen&aacute;rio dos direitos humanos na Am&eacute;rica Latina e no Brasil; (2) Vis&atilde;o internacional sobre a filantropia na Am&eacute;rica Latina e no Brasil; (3) Filantropia de justi&ccedil;a social no Brasil; (4) Filantropia comunit&aacute;ria no cen&aacute;rio internacional e no Brasil; e (5) Mobiliza&ccedil;&atilde;o de recursos e investimento social privado no Brasil.</p>
<p style="text-align: justify;">Os/as autores/as que participam desta obra foram escolhidos/as tendo em vista a diversidade de perfis, de trajet&oacute;rias profissionais e de vida, com capacidade de abordar uma multiplicidade de tem&aacute;ticas vinculadas direta ou indiretamente aos campos da filantropia de justi&ccedil;a social e comunit&aacute;ria tanto a partir de experi&ecirc;ncias pr&aacute;ticas quanto de an&aacute;lises aprofundadas sobre a realidade e os cen&aacute;rios de atua&ccedil;&atilde;o.&nbsp;</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/6821-livrofilantropiadejusticasocial.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF (0.7 MB)</a></p>', '6821-livrofilantropiadejusticasocial.pdf', '2018-10-01', 1, 3, '2018-10-01 13:05:55', '2019-05-02 00:27:43');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (5, 4,  '1982-as-entidades-de-aspsfl-no-brasil.png', 'As Entidades de Assistência Social Privadas sem Fins Lucrativos no Brasil 2013', 'Segunda edição da pesquisa foi realizada em parceria entre o Instituto Brasileiro de Geografia e Estatística - IBGE, e o Ministério do Desenvolvimento Social e Combate à Fome.', '<p style="text-align: justify;">O Instituto Brasileiro de Geografia e Estat&iacute;stica - IBGE, em parceria com o Minist&eacute;rio do Desenvolvimento Social e Combate &agrave; Fome, apresenta, nesta publica&ccedil;&atilde;o, a metodologia aplicada e os resultados da Pesquisa de Entidades de Assist&ecirc;ncia Social Privadas sem Fins Lucrativos - PEAS 2013</p>
<p style="text-align: justify;">A primeira PEAS foi realizada em 2006, e esta segunda edi&ccedil;&atilde;o da pesquisa, com ano de refer&ecirc;ncia 2013, contribui com um novo levantamento estat&iacute;stico sobre o &acirc;mbito da Assist&ecirc;ncia Social privada praticada em todo o Brasil, com importantes mudan&ccedil;as no seu planejamento e forma de execu&ccedil;&atilde;o.</p>
<p style="text-align: justify;">A cargo da Coordena&ccedil;&atilde;o de Popula&ccedil;&atilde;o e Indicadores Sociais da Diretoria de Pesquisas, a PEAS 2013 foi planejada para ser executada em duas fases complementares: as Etapas I e II. A Etapa I, objeto deste volume, orientou-se por verificar e atualizar dados cadastrais, mapear as entidades que pertencem &agrave; &aacute;rea de atua&ccedil;&atilde;o da Assist&ecirc;ncia Social e examinar um conjunto de informa&ccedil;&otilde;es b&aacute;sicas, tais como: p&uacute;blico-alvo, abrang&ecirc;ncia territorial e servi&ccedil;os socioassistenciais prestados. A Etapa II, ainda a ser divulgada, compreende uma gama bem mais ampla e detalhada de informa&ccedil;&otilde;es sobre a atua&ccedil;&atilde;o, a estrutura e o funcionamento das entidades. Em ambas as etapas, a opera&ccedil;&atilde;o de coleta ocorre, exclusivamente, por meio de entrevista telef&ocirc;nica assistida por computador, modalidade de coleta estat&iacute;stica a dist&acirc;ncia, centralizada, utilizada com &ecirc;xito em pesquisas econ&ocirc;micas e de verifica&ccedil;&atilde;o cadastral do IBGE. A PEAS 2013 &eacute;, portanto, a primeira pesquisa social do IBGE nesta modalidade.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/2638-20590-1.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF (0.7 MB)</a></p>', '2638-20590-1.pdf', '2014-01-10', 1, 3, '2018-09-05 13:56:20', '2019-05-02 00:28:31');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (32, 4,  '3051-publicacaopovosindigenas.jpg', 'Fortalecimento dos Povos e das Organizações Indígenas: reflexões e apontamentos', 'Organizada por Paulo Celso de Oliveira Pankararu,livro reúne textos de lideranças indígenas e pesquisadores com reflexões sobre o ambiente jurídico de questões indígenas, como liberdade associativa, tributação e parcerias com o poder público.', '<p>O livro "Fortalecimento dos Povos e das Organizações Indígenas" foi lançado em abril de 2019. A obra é organizada por Paulo Celso de Oliveira Pankararu e resultado de dois encontros sobre o tema promovidos pela Coordenadoria de Pesquisa Jurídica Aplicada (CPJA) da FGV Direito SP, pelo escritório Dora, Azambuja e Oliveira – Advocacia e pelo Grupo de Institutos, Fundações e Empresas (GIFE) no âmbito do projeto Sustentabilidade Econômica das Organizações da Sociedade Civil. O escritório brasileiro da Fundação Ford e outras instituições apoiaram as ações.</p>
<p>Os textos foram elaborados por lideranças indígenas e pesquisadores e trazem reflexões sobre o ambiente jurídico de questões indígenas, como liberdade associativa, tributação e parcerias com o poder público, entre outros pontos.</p>
<h4 class="media-heading">Publicação completa</h4>
<p><a class="btn" title="Baixar a Publicação" href="/cms/arquivos/publications/2638-20590-1.pdf"><img src="/img/botao_pdf.png" width="35" height="35" /></a> <a class="btn" title="Baixar a Publicação" href="/cms/arquivos/publications/2588-povosindigenas2.pdf">Baixar a publicação - PDF (0.5 MB)</a></p>', '2588-povosindigenas2.pdf', '2019-04-30', 1, 3, '2019-05-07 11:03:08', '2019-05-07 11:20:42');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (78, 4,  '3389-veredascovid10.jpg', 'Publicação internacional sobre Covid-19 e OSCs é traduzida para o português', 'Material foi produzido pelo K2P Center, da Universidade de Beirute, no Líbano, e tem entre os objetivos refletir sobre os papeis das organizações da sociedade civil locais e internacionais no combate à pandemia', '<p>O Instituto Veredas e a Funda&ccedil;&atilde;o Oswaldo Cruz (Fiocruz) lan&ccedil;aram a vers&atilde;o em portugu&ecirc;s da edi&ccedil;&atilde;o COVID-19 Rapid Response Series: Strengthening the Role of Local and International NonGovernmental Organizations in Pandemic Responses, Knowledge to Policy, produzida pelo Knowledge to Policy (K2P) Center, da Faculty of Health Sciences American da Universidade de Beirute, no L&iacute;bano. A publica&ccedil;&atilde;o, que no Brasil recebeu o nome de K2P COVID-19 S&eacute;rie de Respostas R&aacute;pidas Fortalecendo o Papel das Organiza&ccedil;&otilde;es N&atilde;oGovernamentais Locais e Internacionais para Respostas &agrave; Pandemia, procura responder &agrave;s seguintes perguntas:</p>
<ul>
<li>Que papeis as ONGs locais e internacionais podem desempenhar nas respostas &agrave; pandemia?</li>
<li>Quais s&atilde;o os modelos existentes de coordena&ccedil;&atilde;o de ONGs em situa&ccedil;&otilde;es de crise?</li>
<li>Que medidas foram adotadas por ONGs de outros pa&iacute;ses para combater o COVID-19?</li>
<li>Como o potencial das ONGs pode ser aproveitado para uma resposta mais eficaz &agrave; pandemia?</li>
</ul>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF" href="/cms/arquivos/publications/1289-veredascovid19compac.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>', '1289-veredascovid19compac.pdf', '2020-06-25', 1, 3, '2020-06-29 21:04:57', '2020-06-29 21:10:18');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (10, 4,  '7408-keyfacts-sobre-investimento-social-brasil.png', 'Censo GIFE 2016: características e tendências na prática dos maiores investidores sociais privados brasileiros', 'Estudo fornece um amplo panorama sobre os institutos e fundações empresariais, familiares, independentes e comunitários que destinam recursos privados para projetos de finalidade pública.', '<p><strong>A exist&ecirc;ncia de informa&ccedil;&otilde;es relevantes, abrangentes e confi&aacute;veis &eacute; fundamental para fortalecer, reconhecer e qualificar o campo do investimento social privado. O Censo GIFE procura dar resposta a essa demanda ao apresentar as principais caracter&iacute;sticas e tend&ecirc;ncias na pr&aacute;tica dos maiores investidores sociais privados brasileiros.</strong></p>
<p>&nbsp;</p>
<p>Realizada desde 2001 com os associados GIFE, a pesquisa aborda uma grande variedade de temas, fornecendo um panorama sobre estrutura, forma de atua&ccedil;&atilde;o, estrat&eacute;gias e programas das empresas e dos institutos e funda&ccedil;&otilde;es empresariais, familiares, independentes e comunit&aacute;rios que destinam recursos privados para projetos de finalidade p&uacute;blica.</p>
<p>Ainda que n&atilde;o contemple o universo total de investidores sociais brasileiros, o Censo GIFE abarca uma quantidade expressiva dessas entidades e tem alcan&ccedil;ado nas &uacute;ltimas edi&ccedil;&otilde;es uma amostra mais representativa do universo dos seus associados, permitindo construir uma s&eacute;rie hist&oacute;rica consistente e de longo prazo que contribua para uma melhor compreens&atilde;o desse campo. Vale dizer que o Censo GIFE 2016 alcan&ccedil;ou a mesma propor&ccedil;&atilde;o de participa&ccedil;&atilde;o da edi&ccedil;&atilde;o passada (90% da base associativa no momento da pesquisa), contemplando 116 organiza&ccedil;&otilde;es respondentes.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/6342-censo-gife2016final1u-ediacaao-atualizada.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF (1.3 MB)</a></p>', '6342-censo-gife2016final1u-ediacaao-atualizada.pdf', '2017-03-09', 1, 3, '2018-09-05 14:45:20', '2019-05-01 23:41:16');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (87, 4,  '7786-oscestrangeira.jpg', 'Conheça o perfil das OSCs estrangeiras em atividade no Brasil', 'Breve estudo do Mapa das OSC mostra que, atualmente, existem 94 organizações em atividade no território nacional registradas sob a natureza jurídica 320-1 (Estabelecimentos no Brasil de Fundação ou Associação estrangeira)', '<p style="text-align: justify;">O ordenamento jur&iacute;dico brasileiro reconhece personalidade jur&iacute;dica &agrave;s pessoas jur&iacute;dicas estrangeiras, desde que respeitem determinadas exig&ecirc;ncias e passem por um procedimento de autoriza&ccedil;&atilde;o de funcionamento. Assim, esse tipo de organiza&ccedil;&atilde;o &eacute; registrada sob a natureza jur&iacute;dica 320-4: <em>Estabelecimentos no Brasil de Funda&ccedil;&atilde;o ou Associa&ccedil;&atilde;o estrangeira</em> (320-4), que representam &ldquo;as filiais, no Brasil, de associa&ccedil;&atilde;o ou funda&ccedil;&atilde;o estrangeiras, ou seja, a associa&ccedil;&atilde;o ou funda&ccedil;&atilde;o constitu&iacute;das de acordo com a legisla&ccedil;&atilde;o estrangeira e que tenha a sede de sua administra&ccedil;&atilde;o no exterior (...); [e] as organiza&ccedil;&otilde;es n&atilde;o-governamentais (ONG), de nacionalidade estrangeira, quando assumirem a natureza jur&iacute;dica de funda&ccedil;&atilde;o privada ou de associa&ccedil;&atilde;o&rdquo;. Atualmente, s&atilde;o 94 organiza&ccedil;&otilde;es desse tipo em atividade no pa&iacute;s. Dashboard produzido pela equipe do Mapa das OSC traz, de maneira ilustrada, algumas das principais caracter&iacute;sticas desse universo, como&nbsp;localiza&ccedil;&atilde;o geogr&aacute;fica, ano de funda&ccedil;&atilde;o e &aacute;rea de atua&ccedil;&atilde;o.</p>
<p style="text-align: justify;">&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF" href="/cms/arquivos/publications/7180-dashboardoscestrangeirasdivulgacao.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>
<p><a href="#_ftn1" name="_ftnref1"></a></p>', '7180-dashboardoscestrangeirasdivulgacao.pdf', '2021-03-16', 1, 3, '2021-03-16 16:58:43', '2021-03-16 17:09:23');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (46, 4,  '4683-censogige2018.jpg', 'GIFE divulga Censo 2018: veja principais dados', 'Pesquisa tem como principal objetivo fornecer um panorama sobre recursos, estrutura, atuação e estratégias sobre o destino de recursos privados para projetos de finalidade pública', '<p><span style="background-color: #ffffff;">O Grupo de Institutos, Funda&ccedil;&otilde;es e Empresas (GIFE) lan&ccedil;ou, em dezembro de 2019, o Censo GIFE 2018. Realizado desde 2001 com associados do Grupo, a pesquisa traz refer&ecirc;ncias ao Mapa das OSC e tem como objetivo fornecer um panorama sobre recursos, estrutura, atua&ccedil;&atilde;o e estrat&eacute;gias sobre o destino de recursos privados para projetos de finalidade p&uacute;blica.</span></p>
<p>&nbsp;</p>
<h4 class="media-heading" style="color: #000000; font-family: Verdana,Arial,Helvetica,sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: bold; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">Publica&ccedil;&atilde;o completa</h4>
<p style="color: #000000; font-family: Verdana,Arial,Helvetica,sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;"><a title="Baixar a publica&ccedil;&atilde;o - PDF" href="/cms/arquivos/publications/4512-censogife2018.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a>&nbsp;</p>
<p>&nbsp;</p>', '', '2019-12-23', 1, 3, '2019-12-23 12:02:37', '2020-01-07 17:40:10');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (15, 4,  '8807-pesquisa-doacao-brasil.png', 'Estudo mapeia os hábitos de doação dos indivíduos no Brasil', 'Pesquisa Doação Brasil é uma iniciativa coordenada pelo IDIS - Instituto pelo Desenvolvimento do Investimento Social, em parceria com um grupo de especialistas e atores relevantes para o campo da cultura de doação no Brasil.', '<p style="text-align: justify;">A "Pesquisa Doa&ccedil;&atilde;o Brasil 2015" &eacute; uma iniciativa coordenada pelo IDIS - Instituto pelo Desenvolvimento do Investimento Social, em parceria com um grupo de especialistas e atores relevantes para o campo da cultura de doa&ccedil;&atilde;o no Brasil.&nbsp;&Eacute; a primeira pesquisa de abrang&ecirc;ncia nacional a mapear os h&aacute;bitos de doa&ccedil;&atilde;o dos indiv&iacute;duos no Brasil. A expectativa &eacute; que ela seja repetida com regularidade e sirva para acompanhar a evolu&ccedil;&atilde;o da cultura de doa&ccedil;&atilde;o no pa&iacute;s.&nbsp;Esta vers&atilde;o traz apenas alguns resultados selecionados.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/2634-pbdidissumario2016.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a Publica&ccedil;&atilde;o - PDF (0.5 MB)</a></p>', '2634-pbdidissumario2016.pdf', '2016-01-25', 1, 3, '2018-09-05 15:18:49', '2019-05-02 00:33:58');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (84, 4,  '7633-artigogife.jpg', 'Como as organizações da sociedade civil alinham suas atividades aos Objetivos do Desenvolvimento Sustentável', 'O estudo foi premiado na 2ª chamada de Artigos GIFE (2020). Objetivo foi verificar de que maneira as OSC têm identificado suas ações e atividades práticas aos ODS, da ONU, de acordo com o preenchimento desses dados no Mapa das OSC', '<p style="text-align: justify;">Os desafios para a implementa&ccedil;&atilde;o e consolida&ccedil;&atilde;o da Agenda 2030, das Organiza&ccedil;&otilde;es das Na&ccedil;&otilde;es Unidas (ONU), se aplicam, em maior ou menor grau, a todos os setores da sociedade. Simultaneamente, verifica-se um di&aacute;logo e converg&ecirc;ncia das finalidades de atua&ccedil;&atilde;o do terceiro setor com as metas contempladas nos 17 Objetivos de Desenvolvimento Sustent&aacute;vel (ODS), o que coloca as organiza&ccedil;&otilde;es da sociedade civil (OSC) na fun&ccedil;&atilde;o de ator social relevante &ndash; e, por que n&atilde;o, protagonista &ndash; nas rela&ccedil;&otilde;es nacionais, globais e multilaterais voltadas para a promo&ccedil;&atilde;o dos ODS. O presente artigo teve como objetivo verificar de que maneira as OSC t&ecirc;m identificado suas a&ccedil;&otilde;es e atividades pr&aacute;ticas aos ODS, de acordo com o preenchimento desses dados no Mapa das OSC (IPEA, 2020). Entre os principais resultados, destaca-se que os dados sistematizados permitem uma melhor compreens&atilde;o e oferecem uma perspectiva organizadora dos elementos que caracterizam as intera&ccedil;&otilde;es entre OSC e ODS.</p>
<p style="text-align: justify;">&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF" href="/cms/arquivos/publications/9338-artigogifeods.pdf" target="_blank"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>', '9338-artigogifeods.pdf', '2020-12-12', 1, 3, '2021-03-16 14:12:42', '2021-03-16 17:11:18');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (11, 4,  '7000-keyfacts-sobre-investimento-social-brasil.png', 'Key facts revela características do investimento social no Brasil', 'Para compreender melhor as características das organizações associadas e suas prioridades de investimento social, o GIFE realiza pesquisa bianual entre seus associados – o Censo GIFE.', '<p style="text-align: justify;">Para compreender melhor as caracter&iacute;sticas das organiza&ccedil;&otilde;es associadas e suas prioridades de investimento social, o GIFE -&nbsp;Grupo de Institutos Funda&ccedil;&otilde;es e Empresas realiza pesquisa bianual entre seus associados &ndash; o Censo GIFE. Este documento destaca os principais resultados da edi&ccedil;&atilde;o de 2017.</p>
<p style="text-align: justify;">O GIFE re&uacute;ne associados de origem empresarial, familiar, independente ou comunit&aacute;ria, que investem em projetos de finalidade p&uacute;blica no Brasil. Neste censo, 116 organiza&ccedil;&otilde;es (90% dos 129 associados do GIFE &agrave; &eacute;poca) responderam a quest&otilde;es relativas a suas atividades e estrutura em 2016. Para fins de an&aacute;lise, os dados de funda&ccedil;&otilde;es e institutos comunit&aacute;rios foram agrupados &agrave;s respostas dos independentes. Todos os dados do Censo, a n&atilde;o ser quando indicado explicitamente, referem-se a 2016 e s&atilde;o baseados nas 116 respostas. Os montantes de investimento est&atilde;o em reais e foram atualizados a dezembro de 2016 pelo IPCA.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/6533-censogife2016keyfacts.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF (0.3 MB)</a></p>', '6533-censogife2016keyfacts.pdf', '2017-05-25', 1, 3, '2018-09-05 14:53:09', '2019-05-02 00:36:59');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (71, 4,  '8767-prosaspesquisa2020.jpg', 'Relatório mostra características de financiamento de editais para OSCs no Brasil', 'Instituto Prosas lançou um estudo realizado com quase 1,7 mil editais com o objetivo de reunir informações sistematizadas sobre o financiamento de iniciativas de interesse público voltadas para as OSCs', '<p>O Instituto Prosas lan&ccedil;ou em maio o Relat&oacute;rio Editais Brasil. Trata-se de um estudo realizado com quase 1,7 mil editais publicados em 2019 com o objetivo de reunir informa&ccedil;&otilde;es sistematizadas sobre o financiamento de iniciativas de interesse p&uacute;blico no pa&iacute;s voltadas para as organiza&ccedil;&otilde;es da sociedade civil. Entre os principais resultados, destaca-se:</p>
<ul>
<li>Em 2019, editais para a &aacute;rea social e a ind&uacute;stria criativa distribu&iacute;ram pelo menos R$ 1,2 bilh&atilde;o para ONGs e artistas do Brasil.</li>
<li>Das 1.675 chamadas mapeadas, 60% tiveram como foco selecionar artistas de diversas linguagens culturais.</li>
<li>Entre as chamadas com foco cultural, a &aacute;rea de audiovisual foi a que recebeu mais incentivos (mais de R$ 87 milh&otilde;es). Jornalismo vem em segundo lugar (cerca de R$ 50 milh&otilde;es), e Artes C&ecirc;nicas e M&uacute;sica praticamente empatam na terceira posi&ccedil;&atilde;o (pouco mais de R$ 33 milh&otilde;es e R$ 32 milh&otilde;es, respectivamente).</li>
</ul>
<h4 class="media-heading">&nbsp;</h4>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF" href="/cms/arquivos/publications/5601-prosascompac.pdf" target="_blank"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>', '5601-prosascompac.pdf', '2020-06-02', 1, 3, '2020-06-08 00:53:52', '2020-06-08 01:01:16');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (16, 4,  '9702-relacao-com-o-estado-na-visa-odas-ongs.png', 'Relação com o estado na visão das ONGs: uma sociologia das percepções', 'Texto do sociólogo Fernando Lima Neto integra o projeto coletivo de pesquisa Estado e Organizações Civis no Brasil, coordenado pelo Ipea com a colaboração de uma rede de diferentes instituições.', '<p style="text-align: justify;">No texto "Rela&ccedil;&atilde;o com o Estado na vis&atilde;o das ONGs: uma sociologia das percep&ccedil;&otilde;es", o autor&nbsp;&nbsp;Fernando Lima Neto&nbsp;discute&nbsp;os resultados da pesquisa realizada pelo N&uacute;cleo Interdisciplinar de Estudos sobre Desigualdades da Universidade Federal do Rio de Janeiro (NIED/UFRJ) sobre percep&ccedil;&otilde;es de dirigentes de organiza&ccedil;&otilde;es n&atilde;o governamentais (ONGs) no que tange &agrave;s rela&ccedil;&otilde;es entre Estado, mercado e sociedade civil no Brasil.</p>
<p style="text-align: justify;">O estudo destaca a&nbsp;rela&ccedil;&atilde;o entre as ONGs e o poder p&uacute;blico, sintetizando-a em uma m&aacute;xima: a parceria com o Estado &eacute; uma via de m&atilde;o dupla. Isso significa que a&nbsp;parceria com o Estado representa a possibilidade de se estabelecer uma&nbsp;a&ccedil;&atilde;o estrat&eacute;gica que potencializa os resultados das ONGs, mas que traz simultaneamente uma s&eacute;rie de obst&aacute;culos e impedimentos burocr&aacute;ticos que comprometem a autonomia dessas institui&ccedil;&otilde;es.</p>
<p style="text-align: justify;">A parceria com o Estado &eacute; vista, ao mesmo tempo, como um dos principais obst&aacute;culos e como uma alavanca para os projetos das ONGs. Nessa aparente contradi&ccedil;&atilde;o, reside uma l&oacute;gica complexa e tensa de representa&ccedil;&otilde;es e valores sociais que norteiam as produ&ccedil;&otilde;es de significado sobre estas organiza&ccedil;&otilde;es.</p>
<p style="text-align: justify;">Assim, o principal objetivo da an&aacute;lise &eacute; identificar regularidades de discurso que permeiam os diferentes perfis de ONG contemplados na pesquisa.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/3686-td1820.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a Publica&ccedil;&atilde;o - PDF (0.2 MB)</a></p>', '3686-td1820.pdf', '2013-03-10', 1, 3, '2018-09-05 15:23:39', '2019-05-02 00:54:08');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (55, 4,  '5370-givingreport2019.jpg', 'Relatório de impacto de 2019 do GivingTuesday já está disponível', 'Documento mostra crescimento exponencial em 2019 em todas as
frente analisadas: dólares, países, comunidades, demografia, mídia social,
e amplitude da narrativa', '<p>O GivingTuesday &eacute; um movimento de lideran&ccedil;a, com uma interconex&atilde;o em rede de l&iacute;deres empresariais que compartilham ideias, li&ccedil;&otilde;es aprendidas,&nbsp;e apoio m&uacute;tuo ao longo do ano. Correspondente ao Dia de Doar no Brasil, &eacute;&nbsp;constitu&iacute;do a partir&nbsp;de uma inova&ccedil;&atilde;o em quatro etapas: aprender, compartilhar, adotar, adaptar. Relat&oacute;rio de 2019 mostra um crescimento exponencial em todas as&nbsp;frentes analisadas: d&oacute;lares, pa&iacute;ses, comunidades, demografia, m&iacute;dia social&nbsp;e amplitude da narrativa.</p>
<p>&nbsp;</p>
<h4 class="media-heading" style="color: #000000; font-family: Verdana,Arial,Helvetica,sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: bold; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">Publica&ccedil;&atilde;o completa</h4>
<p style="color: #000000; font-family: Verdana,Arial,Helvetica,sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;"><a href="/cms/arquivos/publications/1770-givingtuesday2019compac.pdf" target="_blank"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>
<p>&nbsp;</p>', '1770-givingtuesday2019compac.pdf', '2020-03-16', 1, 3, '2020-03-19 14:26:52', '2020-04-15 21:32:02');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (14, 4,  '5353-entenda-o-mrosc-2014.png', 'Entenda o MROSC: Marco Regulatório das Organizações da Sociedade Civil', 'O MROSC (Lei nº 13.019/2014) é uma agenda política ampla, que tem como desafio aperfeiçoar o ambiente jurídico e institucional relacionado às OSCs e suas relações de parceria com o Estado.', '<p style="text-align: justify;">O Marco Regulat&oacute;rio das Organiza&ccedil;&otilde;es da Sociedade Civil (MROSC), como &eacute; conhecida a Lei n&ordm; 13.019/2-14, &eacute; uma agenda pol&iacute;tica ampla, que tem como desafio aperfei&ccedil;oar o ambiente jur&iacute;dico e institucional relacionado &agrave;s organiza&ccedil;&otilde;es da sociedade civil (OSCs) e suas rela&ccedil;&otilde;es de parceria com o Estado.</p>
<p style="text-align: justify;">Conduzido pela Presid&ecirc;ncia da Rep&uacute;blica em permanente di&aacute;logo com organiza&ccedil;&otilde;es da sociedade civil, gestores e especialistas, o trabalho est&aacute; estruturado em tr&ecirc;s eixos:</p>
<ul style="text-align: justify;">
<li>Contratualiza&ccedil;&atilde;o com o poder p&uacute;blico: parcerias com a administra&ccedil;&atilde;o p&uacute;blica em geral, com especial enfoque &agrave; implementa&ccedil;&atilde;o da Lei 13.019/2014;</li>
</ul>
<ul style="text-align: justify;">
<li>Sustentabilidade e certifica&ccedil;&atilde;o: simplifica&ccedil;&atilde;o e desburocratiza&ccedil;&atilde;o do regime tribut&aacute;rio (imunidades e isen&ccedil;&otilde;es incidentes sobre as OSCs, proposta de Simples Social, incentivos fiscais) e dos t&iacute;tulos e certificados outorgados pelo Estado;</li>
</ul>
<ul style="text-align: justify;">
<li>Conhecimento e gest&atilde;o de informa&ccedil;&otilde;es: produ&ccedil;&atilde;o de estudos e pesquisas, semin&aacute;rios, publica&ccedil;&otilde;es, cursos de capacita&ccedil;&atilde;o e dissemina&ccedil;&atilde;o de informa&ccedil;&otilde;es sobre o universo das organiza&ccedil;&otilde;es da sociedade civil e suas parcerias com a administra&ccedil;&atilde;o p&uacute;blica.</li>
</ul>
<p style="text-align: justify;">&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/7245-livretomroscweb.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF (0.4 MB)</a></p>', '7245-livretomroscweb.pdf', '2016-02-01', 1, 3, '2018-09-05 15:12:15', '2019-05-02 00:32:57');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (33, 4,  '1371-td.jpg', 'A atuação das ONGs no Brasil: Análise de transferências federais e projetos executados pelas OSCs no país', 'Estudo inédito baseado nos dados do Mapa das OSCs e do orçamento público federal detalha como as OSCs utilizaram os recursos financeiros captados entre os anos de 2010 a 2018.', '<p>O estudo "Afinal, o que os dados mostram sobre a atua&ccedil;&atilde;o das ONGs? An&aacute;lise de transfer&ecirc;ncias federais e projetos executados pelas Organiza&ccedil;&otilde;es da Sociedade Civil no Brasil" foi produzido em 2019 por pesquisadores da Diretoria de Estudos e Pol&iacute;ticas do Estado, das Institui&ccedil;&otilde;es e da Democracia (Diest), do Instituto de Pol&iacute;tica Econ&ocirc;mica Aplicada - Ipea.&nbsp;O&nbsp;objetivo &eacute; detalhar como as OSCs utilizaram os recursos captados de 2010 a 2018, considerando aspectos como o perfil da organiza&ccedil;&atilde;o, as caracter&iacute;sticas gerais dos projetos desenvolvidos, as &aacute;reas tem&aacute;ticas e a evolu&ccedil;&atilde;o dessas parcerias nos &uacute;ltimos anos. Para tanto, foram consideradas as informa&ccedil;&otilde;es do Mapa das OSCs e do or&ccedil;amento p&uacute;blico federal&nbsp;(2010-2018).</p>
<p style="text-align: justify;">&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF (1.4 MB)" href="/cms/arquivos/publications/4937-tdatuacaodasongs2.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF (1.4 MB)</a></p>
<p>&nbsp;</p>', '4937-tdatuacaodasongs2.pdf', '2019-06-25', 1, 3, '2019-06-24 19:45:51', '2019-06-25 15:42:07');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (80, 4,  '4152-cartilhamrosccovid.jpg', 'Manual orienta Organizações da Sociedade Civil em tempos de Covid-19', 'Publicação foi elaborada pela Plataforma MROSC, uma articulação nacional representativa de diversos movimentos sociais, entidades religiosas, OSC, institutos, fundações privadas e
cooperativas da economia solidária', '<p style="text-align: justify;">A Plataforma por um Novo Marco Regulat&oacute;rio das Organiza&ccedil;&otilde;es da Sociedade Civil (Plataforma MROSC) lan&ccedil;ou o&nbsp;<em>Manual Pr&aacute;tico de Apoio &agrave;s Organiza&ccedil;&otilde;es da Sociedade Civil: MROSC &amp; Covid 19. </em>O objetivo da publica&ccedil;&atilde;o &eacute;&nbsp;tra&ccedil;ar um roteiro de apoio aos processos de tomada de decis&atilde;o das organiza&ccedil;&otilde;es da sociedade civil (OSC) nas rela&ccedil;&otilde;es de parceria firmadas com o poder p&uacute;blico com base na Lei n&ordm;. 13.019/2014 &ndash; MROSC, com informa&ccedil;&otilde;es sobre cada uma das etapas de desenvolvimento da rela&ccedil;&atilde;o de parceria: planejamento, sele&ccedil;&atilde;o e celebra&ccedil;&atilde;o, execu&ccedil;&atilde;o, monitoramento e presta&ccedil;&atilde;o de contas.</p>
<p style="text-align: justify;">A Plataforma MROSC &eacute; uma articula&ccedil;&atilde;o nacional representativa de diversos movimentos sociais, entidades religiosas, OSC, institutos, funda&ccedil;&otilde;es privadas e cooperativas da economia solid&aacute;ria, composta por mais de 1000 organiza&ccedil;&otilde;es signat&aacute;rias, 199 articula&ccedil;&otilde;es/redes/grupos, 11 f&oacute;runs e 6 plataformas estaduais, criada em 2010 com a finalidade de definir uma agenda comum de incid&ecirc;ncia da sociedade civil brasileira, em prol da melhoria de seu ambiente de atua&ccedil;&atilde;o, seja pela regula&ccedil;&atilde;o, seja por produ&ccedil;&atilde;o e apropria&ccedil;&atilde;o de conhecimentos, cuja rede indireta alcan&ccedil;a mais de 50 mil entidades.</p>
<p style="text-align: justify;">&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="PDF" href="/cms/arquivos/publications/7189-cartilhamrosccovidcompac.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>
<p style="text-align: justify;">&nbsp;</p>
<p style="text-align: justify;">&nbsp;</p>', '7189-cartilhamrosccovidcompac.pdf', '2020-06-28', 1, 3, '2020-06-29 21:23:08', '2020-06-29 21:33:52');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (6, 4,  '7133-tudo-que-vc-precisa-saber-antes-de-escrever-sobre-ongs.png', 'Manual orienta jornalistas para escrever sobre ONGs', 'Com uma linguagem fácil e ilustrada, a obra "Tudo que você precisa saber antes de escrever sobre ONGs" traz informações básicas sobre o universo do terceiro setor.', '<p style="text-align: justify;">Pode n&atilde;o parecer, mas a imprensa e as Organiza&ccedil;&otilde;es da Sociedade Civil (OSCs) t&ecirc;m muito em comum. S&atilde;o dois atores fundamentais para a democracia, que praticam o controle social, fiscalizam e cobram o poder p&uacute;blico. Aproximar estes dois setores t&atilde;o importantes &eacute; um passo necess&aacute;rio para a constru&ccedil;&atilde;o de uma sociedade mais participativa e aberta. Com esse objetivo, a publica&ccedil;&atilde;o "Tudo que voc&ecirc; precisa saber antes de escrever sobre ONGs" procura&nbsp;fornecer aos/&agrave;s jornalistas as informa&ccedil;&otilde;es&nbsp;b&aacute;sicas para entender o complexo universo das&nbsp;OSCs.&nbsp;</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/7663-23785-2-cp-min.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a Publica&ccedil;&atilde;o - PDF (1.4 MB)</a></p>', '7663-23785-2-cp-min.pdf', '2016-03-10', 1, 3, '2018-09-05 14:24:25', '2019-05-02 00:38:15');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (79, 4,  '1504-mroscavancosdesafios.jpg', 'Coletânea traz série de artigos sobre avanços e desafios do MROSC', 'Publicação foi desenvolvida pelo Grupo de Institutos, Fundações e Empresas (GIFE) em parceria com a Coordenadoria de Pesquisa Jurídica Aplicada (CPJA) da FGV Direito SP e com o Instituto de Pesquisa Econômica Aplicada (IPEA)', '<p style="text-align: justify;">O livro <em>Marco Regulat&oacute;rio das Organiza&ccedil;&otilde;es da Sociedade Civil: avan&ccedil;os e desafios</em>, lan&ccedil;ado no dia 25 de junho de 2020, integra a cole&ccedil;&atilde;o Sustentabilidade Econ&ocirc;mica das Organiza&ccedil;&otilde;es da Sociedade Civil e apresenta os resultados das pesquisas desenvolvidas no &acirc;mbito do projeto de mesmo t&iacute;tulo, desenvolvido pelo Grupo de Institutos, Funda&ccedil;&otilde;es e Empresas (GIFE) em parceria com a Coordenadoria de Pesquisa Jur&iacute;dica Aplicada (CPJA) da FGV Direito SP e com o Instituto de Pesquisa Econ&ocirc;mica Aplicada (IPEA). O projeto conta com o apoio financeiro da Uni&atilde;o Europeia, do Instituto Arapya&uacute;, do Instituto de Cidadania Empresarial (ICE), da Laudes Foundation e da Funda&ccedil;&atilde;o Lemann.</p>
<p style="text-align: justify;">Com dura&ccedil;&atilde;o de tr&ecirc;s anos (2017-2019), o projeto tem como foco investigar quatro subtemas relacionados &agrave; sustentabilidade econ&ocirc;mica das organiza&ccedil;&otilde;es da sociedade civil (OSCs): 1) a implementa&ccedil;&atilde;o da Lei n&deg; 13.019/2014 (Marco Regulat&oacute;rio das OSCs &ndash; MROSC); 2) as barreiras tribut&aacute;rias a doa&ccedil;&otilde;es &agrave;s OSCs (imposto sobre transmiss&atilde;o causa mortis e doa&ccedil;&atilde;o &ndash; ITCMD); 3) os incentivos a doa&ccedil;&otilde;es de pessoas f&iacute;sicas &agrave;s OSCs; al&eacute;m dos 4) fundos patrimoniais.</p>
<h4 class="media-heading">&nbsp;</h4>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF" href="/cms/arquivos/publications/8638-mroscavancosdesafioscompac.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>', '8638-mroscavancosdesafioscompac.pdf', '2020-06-26', 1, 3, '2020-06-29 21:12:17', '2020-06-29 21:35:52');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (8, 4,  '6171-participacao-das-ongs-nas-pp.png', 'Participação das ONGs nas políticas públicas: o ponto de vista de gestores federais', 'Com base em 53 entrevistas, o estudo analisa percepções de gestores da alta burocracia quanto à decisão de implementar políticas públicas por meio da cooperação com a sociedade civil.', '<p style="text-align: justify;">Com base em 53 entrevistas semidiretivas, o texto "A participa&ccedil;&atilde;o das ONGs nas pol&iacute;ticas p&uacute;blicas: o ponto de vista de gestores federais", de Felix Garcia Lopes e Rafael Abreu, analisa percep&ccedil;&otilde;es de gestores da alta burocracia federal quanto &agrave; decis&atilde;o de implementar pol&iacute;ticas p&uacute;blicas por meio da coopera&ccedil;&atilde;o com Organiza&ccedil;&otilde;es da Sociedade Civil (OSCs).</p>
<p style="text-align: justify;">Sistematiza-se os motivos que justificam a coopera&ccedil;&atilde;o, as vantagens e desvantagens da implementa&ccedil;&atilde;o por meio de ONGs em face da burocracia p&uacute;blica e dos pap&eacute;is relativos atribu&iacute;dos &agrave; burocracia e &agrave;s ONGs nas pol&iacute;ticas federais.</p>
<p style="text-align: justify;">Os resultados apontam que os gestores entrevistados atribuem &agrave;s organiza&ccedil;&otilde;es civis fun&ccedil;&otilde;es e compet&ecirc;ncias que a burocracia n&atilde;o poder&aacute; substituir no curto e m&eacute;dio prazos, tais como expertise, capilaridade, flexibilidade e engajamento nas pol&iacute;ticas mencionadas. Mas a burocracia &eacute; considerada indispens&aacute;vel &agrave; implementa&ccedil;&atilde;o bem-sucedida das pol&iacute;ticas, por ter quadros permanentes e melhor infraestrutura, condi&ccedil;&atilde;o complementar &agrave; continuidade e institucionaliza&ccedil;&atilde;o das pol&iacute;ticas.</p>
<p style="text-align: justify;">Estas distin&ccedil;&otilde;es retratam vis&otilde;es que diferem daquelas que constitu&iacute;ram o arcabou&ccedil;o do modelo neoliberal, nos anos 1990, no qual os apelos &agrave; efici&ecirc;ncia, pela via da delega&ccedil;&atilde;o estatal &agrave;s organiza&ccedil;&otilde;es civis, constitu&iacute;ram o n&uacute;cleo das reformas legislativas visando maior engajamento das ONGs nas pol&iacute;ticas. Hoje, as organiza&ccedil;&otilde;es s&atilde;o consideradas uma via para refor&ccedil;ar ou fortalecer pol&iacute;ticas do Estado, e n&atilde;o como substitutas a elas.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a class="btn" title="Baixar a Publica&ccedil;&atilde;o" href="/cms/arquivos/publications/1019-24179-2.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a Publica&ccedil;&atilde;o - PDF (0.5 MB)</a></p>', '1019-24179-2.pdf', '2016-05-16', 1, 3, '2018-09-05 14:33:08', '2019-05-02 00:43:34');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (34, 4,  '2053-bapi.jpg', 'Publicação reúne artigos científicos sobre o terceiro setor', 'Características e definições das OSCs, mecanismos de fortalecimento da transparência, trabalho, estratégias financeiras e sustentabilidade são alguns temas presentes no Boletim de Análise Político-Institucional (BAPI)', '<p>Contemplar distintas dimens&otilde;es que comp&otilde;em o debate sobre OSCs no pa&iacute;s privilegiando a diversidade de perspectivas anal&iacute;ticas e institucionais. Esse &eacute; o principal objetivo da nova edi&ccedil;&atilde;o do <em>Boletim de An&aacute;lise Pol&iacute;tico-Institucional&nbsp;</em>(BAPI). A publica&ccedil;&atilde;o re&uacute;ne pesquisadores e pesquisadoras de diversas institui&ccedil;&otilde;es de modo a explicitar a complexidade que o debate sobre a atua&ccedil;&atilde;o das OSCs tem assumido no Brasil no per&iacute;odo recente e os m&uacute;ltiplos esfor&ccedil;os em andamento para ampliar, aprimorar e qualificar o conhecimento produzido sobre o setor.</p>
<p>Composta por onze artigos, a edi&ccedil;&atilde;o &eacute; dividida em tr&ecirc;s partes. A primeira, intitulada&nbsp;<em>O que sabemos sobre as Organiza&ccedil;&otilde;es da Sociedade Civil? Estudos sobre o perfil das OSCs e mecanismos de fortalecimento da transpar&ecirc;ncia</em>&nbsp;<em>no Brasil,</em>&nbsp;apresenta as principais fontes de informa&ccedil;&atilde;o sobre OSCs no pa&iacute;s que, em conjunto com o Mapa das OSCs (Ipea) e o <em>Perfil das OSCs no Brasil</em> (lan&ccedil;ado em 2018), constituem o panorama mais completo de dados sobre o setor na atualidade. A segunda parte,&nbsp;<em>Trabalho nas OSCs: avan&ccedil;os e desafios,</em>&nbsp;aborda diferentes dimens&otilde;es que configuram as rela&ccedil;&otilde;es formais de trabalho no interior das OSCs. A &uacute;ltima parte,&nbsp;<em>Sustentabilidade das OSCs: estrat&eacute;gias e limites,&nbsp;</em>abrange um rol amplo de quest&otilde;es que tem marcado o debate sobre os principais desafios enfrentados pelo setor considerando a redu&ccedil;&atilde;o de investimentos p&uacute;blicos e privados direcionados para as OSCs no per&iacute;odo recente.</p>
<p>O BAPI &eacute; uma publica&ccedil;&atilde;o do Instituto de Pesquisa Econ&ocirc;mica Aplicada (Ipea). Esta edi&ccedil;&atilde;o tem&aacute;tica foi motivada tamb&eacute;m pelas reflex&otilde;es travadas no &acirc;mbito do Grupo de Conhecimento no Investimento Social Privado (ISP). Formado em 2018, o Grupo re&uacute;ne entidades de refer&ecirc;ncia relacionadas &agrave; produ&ccedil;&atilde;o de dados e informa&ccedil;&otilde;es sobre o campo do ISP e das OSCs para estimular um ambiente de troca, articula&ccedil;&atilde;o e coopera&ccedil;&atilde;o que possibilite uma atua&ccedil;&atilde;o mais organizada no terceiro setor. Participam do grupo entidades como Associa&ccedil;&atilde;o Brasileira de Captadores de Recurso (ABCR), Comunitas; Funda&ccedil;&atilde;o Getulio Vargas (FGV); Grupo de Institui&ccedil;&otilde;es, Funda&ccedil;&otilde;es e Empresas (GIFE); Instituto Brasileiro de Geografia e Estat&iacute;stica (IBGE); Instituto de Cidadania Empresarial (ICE), Instituto para o Desenvolvimento do Investimento Social (IDIS); Instituto de Pesquisa Econ&ocirc;mica Aplicada (IPEA); Programa das Na&ccedil;&otilde;es Unidas para o Desenvolvimento (PNUD), Rede de Filantropia para a Justi&ccedil;a Social e Wings, Plataforma Prosas.</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF" href="http://www.ipea.gov.br/portal/images/stories/PDFs/boletim_analise_politico/190717_bapi_20.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>
<p>&nbsp;</p>', '', '2019-07-17', 1, 3, '2019-07-23 14:50:16', '2019-07-23 14:57:10');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (74, 4,  '7229-ntcoronavirusoscs.jpg', 'Nota técnica do Ipea aborda impactos da Covid-19 nas OSCs', 'Objetivo é destacar os impactos imediatos e desafios que a crise causada pelo coronavírus tem imposto às organizações da sociedade civil brasileiras, apontar alternativas e refletir sobre perspectivas', '<p>O Ipea lan&ccedil;ou no dia 5 de junho de 2020 uma nota t&eacute;cnica (NT) com o objetivo de destacar os impactos imediatos que a crise causada pelo coronav&iacute;rus tem imposto &agrave;s OSCs brasileiras, apontar alternativas e refletir sobre perspectivas, em um esfor&ccedil;o de contextualiza&ccedil;&atilde;o a partir de mapeamentos e descri&ccedil;&otilde;es de perfis das organiza&ccedil;&otilde;es em atividades no pa&iacute;s, usando como fonte, especialmente, o Mapa das OSCs.</p>
<p>O texto est&aacute; dividido em duas partes principais. A primeira tem como proposta tra&ccedil;ar um panorama contextual quantitativo das OSCs das &aacute;reas de sa&uacute;de, assist&ecirc;ncia social e desenvolvimento e defesa de direitos e interesses e casos confirmados e de &oacute;bitos decorrentes da Covid-19, de acordo com territ&oacute;rio, popula&ccedil;&atilde;o, IDH. A segunda parte se estrutura em subse&ccedil;&otilde;es que discutem: 1) movimenta&ccedil;&otilde;es de recursos financeiros; 2) doa&ccedil;&otilde;es e mobiliza&ccedil;&otilde;es para pessoas em situa&ccedil;&atilde;o de vulnerabilidade e hospitais; 3) mudan&ccedil;a estrat&eacute;gica nas atividades; 4) atos normativos e impactos jur&iacute;dicos-legais; e 5) comunica&ccedil;&atilde;o, visibilidade e <em>advocacy</em>.</p>
<p>&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF" href="/cms/arquivos/publications/7210-ntcoronavirusoscscompressed.pdf" target="_blank"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>', '7210-ntcoronavirusoscscompressed.pdf', '2020-06-05', 1, 3, '2020-06-08 01:16:19', '2020-06-08 01:22:08');
INSERT INTO cmsosc.posts (id, categoria_id, imagem, titulo, resumida, descricao, arquivo, data, status, cmsuser_id, created_at, updated_at) VALUES (65, 4,  '9094-covid19sbsa.jpg', 'Coronavirus & OSCs: cartilha informa sobre os impactos das medidas legais no dia a dia das organizações', 'Objetivo é discorrer sobre os atos normativos decorrentes da declaração de pandemia e de calamidade pública no Brasil em razão do coronavírus para que OSCs estejam aptas a enfrentar os desafios legais', '<p style="text-align: justify;">A cartilha &ldquo;OSC e COVID-19: impactos das medidas legais no dia a dia das organiza&ccedil;&otilde;es da sociedade civil&rdquo;, publicada pelo escrit&oacute;rio SBSA Advogados, prop&otilde;e uma sistematiza&ccedil;&atilde;o dos&nbsp;atos normativos decorrentes da declara&ccedil;&atilde;o de pandemia e de calamidade p&uacute;blica no Brasil em raz&atilde;o do coronav&iacute;rus. O objetivo &eacute; contribuir com informa&ccedil;&otilde;es para que as organiza&ccedil;&otilde;es da sociedade civil e os agentes p&uacute;blicos e privados lidem com os desafios impostos pela situa&ccedil;&atilde;o, sem descuidar das garantias constitucionais e do cumprimento de obriga&ccedil;&otilde;es legais.</p>
<p style="text-align: justify;">&nbsp;</p>
<h4 class="media-heading">Publica&ccedil;&atilde;o completa</h4>
<p><a title="Baixar a publica&ccedil;&atilde;o - PDF" href="/cms/arquivos/publications/7546-covid19cartilhasbsacompac.pdf"><img src="/img/botao_pdf.png" width="35" height="35" />Baixar a publica&ccedil;&atilde;o - PDF</a></p>
<p>&nbsp;</p>', '7546-covid19cartilhasbsacompac.pdf', '2020-04-15', 1, 3, '2020-04-15 21:22:04', '2020-06-29 21:36:23');