CREATE IF NOT EXISTS SCHEMA GRAPH;

CREATE TABLE graph.tb_cnes(
	id_cnes SERIAL NOT NULL,
	nu_cnpj_requerente TEXT, 
	no_pessoa TEXT, 
	no_regiao TEXT, 
	sg_uf TEXT, 
	no_municipio TEXT, 
	a_lei TEXT, 
	tempestividade TEXT, 
	nu_sipar TEXT, 
	dt_protocolo TEXT, 
	dt_protocolo_menor TEXT, 
	assunto TEXT, 
	cebas_atual TEXT, 
	inicio_validade_anterior TEXT, 
	fim_validade_anterior TEXT, 
	cnes TEXT, 
	co_cnes TEXT, 
	nu_cnpj TEXT, 
	nu_cnpj_mantenedora TEXT, 
	no_razao_social TEXT, 
	no_fantasia TEXT, 
	regiao TEXT, 
	uf TEXT, 
	co_municipio TEXT, 
	municipio TEXT, 
	no_logradouro TEXT, 
	nu_endereco TEXT, 
	no_complemento TEXT, 
	no_bairro TEXT, 
	co_cep TEXT, 
	co_natureza_jur TEXT, 
	ds_natureza_juridica TEXT, 
	ds_retencao_tributo TEXT, 
	ds_motivo_desab TEXT, 
	co_natureza_organizacao TEXT, 
	ds_natureza_organizacao TEXT, 
	co_esfera_administrativa TEXT, 
	ds_esfera_administrativa TEXT, 
	ds_tipo_unidade TEXT, 
	ds_gestao TEXT, 
	st_registro_ativo TEXT, 
	CONSTRAINT pk_tb_cnes PRIMARY KEY (id_cnes)
);
