# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres-db-postigis-2.5:
    container_name: postgres-db-postigis-2.5
    image: postgis/postgis:12-2.5
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432
    volumes:
      - db-ipea-data:/var/lib/postgresql/data

networks:
  dev-net:
    external: true

volumes:
  db-ipea-data:
