SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 593066::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"24/07/2001","dt_fim_certificado":"18/3/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 510180::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"10/01/2006","dt_fim_certificado":"04/02/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 789366::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"02/05/2005","dt_fim_certificado":"17/3/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 606456::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"28/03/2005","dt_fim_certificado":"03/03/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 640268::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"08/06/2006","dt_fim_certificado":"10/2/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 642087::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"02/10/2008","dt_fim_certificado":"23/3/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 479404::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"14/01/2008","dt_fim_certificado":"11/3/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 731357::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"13/01/2010","dt_fim_certificado":"24/2/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 762436::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"24/08/2015","dt_fim_certificado":"17/03/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 603741::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"29/11/2013","dt_fim_certificado":"10/03/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 787586::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"03/11/2014","dt_fim_certificado":"04/02/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 786918::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"29/12/2015","dt_fim_certificado":"10/2/2021","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);


SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 403162::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"20/02/2009","dt_fim_certificado":"08/01/21","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 446530::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"28/12/2005","dt_fim_certificado":"25/01/21","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 786652::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"07/12/2010","dt_fim_certificado":"08/01/21","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 654069::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"30/11/2004","dt_fim_certificado":"08/01/21","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 788819::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"24/01/2011","dt_fim_certificado":"09/12/20","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 782724::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"29/05/2009","dt_fim_certificado":"07/12/20","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 767465::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"09/05/2007","dt_fim_certificado":"08/01/21","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 586723::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"09/06/2008","dt_fim_certificado":"08/01/21","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 786673::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"18/04/2012","dt_fim_certificado":"08/01/21","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 550851::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"30/06/2016","dt_fim_certificado":"30/12/20","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 615229::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"26/04/2013","dt_fim_certificado":"08/01/21","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 639278::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"18/11/2014","dt_fim_certificado":"25/01/21","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);
SELECT * FROM portal.atualizar_certificado_osc('MJSP'::TEXT, 786979::NUMERIC, 'id_osc'::TEXT, now()::TIMESTAMP, '[{"cd_certificado":4, "dt_inicio_certificado":"31/10/2008","dt_fim_certificado":"08/01/21","cd_municipio":null,"cd_uf":null}]'::JSONB, TRUE::BOOLEAN, TRUE::BOOLEAN, TRUE::BOOLEAN, NULL::INTEGER, 3::INTEGER);