REFRESH MATERIALIZED VIEW CONCURRENTLY osc.vw_busca_resultado;
REFRESH MATERIALIZED VIEW CONCURRENTLY portal.vw_osc_dados_gerais;
REFRESH MATERIALIZED VIEW CONCURRENTLY portal.vw_osc_descricao;
REFRESH MATERIALIZED VIEW CONCURRENTLY portal.vw_log_alteracao;
